### ISSUE TITLE
你好，有后端么？

### ISSUE THREAD

**Issue by thup** [EziosWJ/vux2-hae#5]
你好，我在本地起了服务，但是没有后端无法预览

**Comment by EziosWJ** [comment]
https://github.com/EziosWJ/helpTeach

**Comment by EziosWJ** [comment]
> 你好，我在本地起了服务，但是没有后端无法预览

sql在根目录，配置文件在resource下的a_little_那个txt文件

**Comment by thup** [comment]
谢谢

**Comment by EziosWJ** [comment]
> 谢谢

不客气，有问题联系我qq 656876071

**Comment by thup** [comment]
你好，我想通过post/put请求向后端发送json数据，但是将相关文件中的headers:{"Content-Type":"multipart/form-data"}修改为了headers:{'Content-Type':'application/json'},，却还是表单数据，请问这是怎么回事？
![image](https://user-images.githubusercontent.com/30685788/124379469-d7be5d80-dce9-11eb-95a5-95b9ee32bc70.png)

**Comment by thup** [comment]
> 你好，我想通过post/put请求向后端发送json数据，但是将相关文件中的headers:{"Content-Type":"multipart/form-data"}修改为了headers:{'Content-Type':'application/json'},，却还是表单数据，请问这是怎么回事？
> ![image](https://user-images.githubusercontent.com/30685788/124379469-d7be5d80-dce9-11eb-95a5-95b9ee32bc70.png)

终于解决了，把qs相关的东西全删除了，然后就好了
